# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_location', models.FilePathField()),
                ('record_type', models.CharField(max_length=100)),
            ],
        ),
    ]
