# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirginiaPrinting', '0002_auto_20171028_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='pdf_location',
            field=models.FilePathField(path='~/PycharmProjects/VPDB/static/biographies'),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='pdf_location',
            field=models.FilePathField(path='~/PycharmProjects/VPDB/static/imprints'),
        ),
        migrations.AlterField(
            model_name='newspapercitation',
            name='pdf_location',
            field=models.FilePathField(path='~/PycharmProjects/VPDB/static/journal_citations'),
        ),
        migrations.AlterField(
            model_name='newspaperhistory',
            name='pdf_location',
            field=models.FilePathField(path='~/PycharmProjects/VPDB/static/journal_histories'),
        ),
    ]
