# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirginiaPrinting', '0004_auto_20171106_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprintrecord',
            name='imprint_number',
            field=models.DecimalField(decimal_places=3, max_digits=7, primary_key=True, serialize=False),
        ),
    ]
