# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirginiaPrinting', '0007_auto_20171120_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imprintrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspapercitation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspaperhistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='_biography_associates_+', to='VirginiaPrinting.Biography'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='function',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='biography',
            name='locales',
            field=models.CharField(blank=True, default='Virginia', max_length=200),
        ),
        migrations.AlterField(
            model_name='biography',
            name='pdf_location',
            field=models.FilePathField(blank=True, path='~/PycharmProjects/VPDB/static/biographies'),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='associates',
            field=models.ManyToManyField(blank=True, to='VirginiaPrinting.Biography'),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='description',
            field=models.CharField(blank=True, default='Unrecorded', max_length=200),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='issuing_press',
            field=models.CharField(blank=True, default='Uncertain', max_length=200),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='pdf_location',
            field=models.FilePathField(blank=True, path='static/imprints'),
        ),
        migrations.AlterField(
            model_name='imprintrecord',
            name='place_issued',
            field=models.CharField(blank=True, default='Virginia', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspapercitation',
            name='associates',
            field=models.ManyToManyField(blank=True, to='VirginiaPrinting.Biography'),
        ),
        migrations.AlterField(
            model_name='newspapercitation',
            name='pdf_location',
            field=models.FilePathField(blank=True, path='~/PycharmProjects/VPDB/static/journal_citations'),
        ),
        migrations.AlterField(
            model_name='newspapercitation',
            name='proprietors',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspaperhistory',
            name='pdf_location',
            field=models.FilePathField(blank=True, path='~/PycharmProjects/VPDB/static/journal_histories'),
        ),
    ]
